version: '3.9'
services:
  web:
    container_name: 'django-app'
    build: .
    ports:
      - 8000:8000
    volumes:
      - django-todo-volume:/app

  db:
    container_name: 'mysql_container'
    image: mysql:5.7
    ports:
      - 3306:3006
    environment:
      MYSQL_ROOT_PASSWORD: 'test@123'
volumes:
  django-todo-volume:
